default:
  smtp_server: smtp.gmail.com
  smtp_port: 587

development:
  email_address: ReleaseMe dev <info@releaseme.be>
  domain: localhost:3000
  app_name: ReleaseMe dev

test:
  email_address: ReleaseMe test <info@releaseme.be>
  domain: localhost:3000
  app_name: ReleaseMe test

production:
  email_address: ReleaseMe <info@releaseme.be>
  domain: releaseme.be
  app_name: ReleaseMe
