require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IntegrationsController do

  # This should return the minimal set of attributes required to create a valid
  # Integration. As you add validations to Integration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IntegrationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all integrations as @integrations" do
      integration = Integration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:integrations).should eq([integration])
    end
  end

  describe "GET show" do
    it "assigns the requested integration as @integration" do
      integration = Integration.create! valid_attributes
      get :show, {:id => integration.to_param}, valid_session
      assigns(:integration).should eq(integration)
    end
  end

  describe "GET new" do
    it "assigns a new integration as @integration" do
      get :new, {}, valid_session
      assigns(:integration).should be_a_new(Integration)
    end
  end

  describe "GET edit" do
    it "assigns the requested integration as @integration" do
      integration = Integration.create! valid_attributes
      get :edit, {:id => integration.to_param}, valid_session
      assigns(:integration).should eq(integration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Integration" do
        expect {
          post :create, {:integration => valid_attributes}, valid_session
        }.to change(Integration, :count).by(1)
      end

      it "assigns a newly created integration as @integration" do
        post :create, {:integration => valid_attributes}, valid_session
        assigns(:integration).should be_a(Integration)
        assigns(:integration).should be_persisted
      end

      it "redirects to the created integration" do
        post :create, {:integration => valid_attributes}, valid_session
        response.should redirect_to(Integration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved integration as @integration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Integration.any_instance.stub(:save).and_return(false)
        post :create, {:integration => { "url" => "invalid value" }}, valid_session
        assigns(:integration).should be_a_new(Integration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Integration.any_instance.stub(:save).and_return(false)
        post :create, {:integration => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested integration" do
        integration = Integration.create! valid_attributes
        # Assuming there are no other integrations in the database, this
        # specifies that the Integration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Integration.any_instance.should_receive(:update_attributes).with({ "url" => "MyString" })
        put :update, {:id => integration.to_param, :integration => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested integration as @integration" do
        integration = Integration.create! valid_attributes
        put :update, {:id => integration.to_param, :integration => valid_attributes}, valid_session
        assigns(:integration).should eq(integration)
      end

      it "redirects to the integration" do
        integration = Integration.create! valid_attributes
        put :update, {:id => integration.to_param, :integration => valid_attributes}, valid_session
        response.should redirect_to(integration)
      end
    end

    describe "with invalid params" do
      it "assigns the integration as @integration" do
        integration = Integration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Integration.any_instance.stub(:save).and_return(false)
        put :update, {:id => integration.to_param, :integration => { "url" => "invalid value" }}, valid_session
        assigns(:integration).should eq(integration)
      end

      it "re-renders the 'edit' template" do
        integration = Integration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Integration.any_instance.stub(:save).and_return(false)
        put :update, {:id => integration.to_param, :integration => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested integration" do
      integration = Integration.create! valid_attributes
      expect {
        delete :destroy, {:id => integration.to_param}, valid_session
      }.to change(Integration, :count).by(-1)
    end

    it "redirects to the integrations list" do
      integration = Integration.create! valid_attributes
      delete :destroy, {:id => integration.to_param}, valid_session
      response.should redirect_to(integrations_url)
    end
  end

end
